# Generated by Django 5.1 on 2024-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble_app', '0002_alter_user_tipo_usuario_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
