# Generated by Django 5.1 on 2024-09-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble_app', '0003_inmueble_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
    ]
